//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public int DishID { get; set; }
        public int UserID { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Ammount { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Restaurant_Users Restaurant_Users { get; set; }
    }
}
