//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantUserDatabaseEntities : DbContext
    {
        public RestaurantUserDatabaseEntities()
            : base("name=RestaurantUserDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Restaurant_Users> Restaurant_Users { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<Review> ReviewSet { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Card> Card { get; set; }
    }
}
